image: maven:3.8.3-openjdk-17

include:
- project: $PIPELINE_TEMPLATES_REPO_PATH
  ref: $PIPELINE_TEMPLATES_REPO_BRANCH
  file: $PIPELINE_TEMPLATES_BACKEND_JAVA_FILENAME

variables:
  SERVICE_LOCATION: ''
  IMAGE_LOCATION: backend
  HELM_CHART_VALUES_LOCATION: rft-devtools
  JAVA_VERSION: 17
