apiVersion: v1
kind: Service
metadata:
  name: kafka-rest-proxy
spec:
  selector:
    app.kubernetes.io/name: kafka-rest-proxy
  ports:
    - name: http
      port: 8082
      targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-rest-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kafka-rest-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kafka-rest-proxy
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kafka-rest-proxy
          image: confluentinc/cp-kafka-rest:7.4.4
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8082
          env:
            - name: KAFKA_REST_HOST_NAME
              value: kafka-rest-proxy
            - name: KAFKA_REST_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka.kafka-shared.svc.cluster.local:9092
            - name: KAFKA_REST_LISTENERS
              value: http://0.0.0.0:8082
            - name: KAFKA_REST_SCHEMA_REGISTRY_URL
              value: http://schema-registry.kafka-shared.svc.cluster.local:8081
            - name: KAFKAREST_HEAP_OPTS
              value: -Xms128m -Xmx384m
          readinessProbe:
            httpGet:
              path: /topics
              port: http
            initialDelaySeconds: 25
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /topics
              port: http
            initialDelaySeconds: 75
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 640Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
